### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by SivaBodapati** [saGar-GG/Paddy-leaf-diseases-detection#1]
provide ../modelsss/efficientnetb3-paddy-disease-detection-97.31.h5 file

**Comment by saGar-GG** [comment]
Too large. Cannot add here

**Comment by SivaBodapati** [comment]
provide : efficientnetb3-paddy-disease-detection-97.31.h5 
mail id:- 191fa07001p@gmail.com 
send it to my mail id
